
export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_ERROR = 'LOAD_ARTICLES_ERROR';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const ARTICLE_CLOSED = 'ARTICLE_CLOSED';